env:
  node: true
  es2021: true

 extends: airnbnb-base

 parserOptions:
   ecmaVersion: latest
  sourseType: module

 rules:
   no-console: off
   import/extensions: off
  semi: off
  indent: off
  eqeqeq: off
  prefer-const: off
  keyword-spacing: off
  space-before-blocks: off
  linebreak-style: off


