env:
  node: true
  es2021: true

 extends: airnbnb-base

 parserOptions:
   ecmaVersion: latest
  sourseType: module

 rules:
   no-console: off
   import/extensions: off

build: {
  extend(config, ctx) {
    config.module.rules.push({
      enforce: 'pre',
      test: /\.(js|vue)$/,
      loader: 'eslint-loader',
      exclude: /(node_modules)/,
      options: {
        fix: true
      }
    })
  }
}
