env:
  node: true
  es2021: true

 extends: airnbnb-base

 parserOptions:
   ecmaVersion: latest
  sourseType: module

 rules:
   no-console: off
   import/extensions: off

ignorePatterns: 
  -games
  -bin